# placeholder file. Replace this with your existing one if it exists.
[containers]
# Set time zone in container. Takes IANA time zones as well as "local",
# which sets the time zone in the container to match the host machine.
#
# tz = 'Europe/London'
# tz = 'America/Chicago'
# tz = "local"

[engine]
# compose_providers = ["podman-compose"]
# env = []

[machine]
# Use applehv so CLI sees the same machine as Podman Desktop (Desktop uses Apple Hypervisor)
# provider = "applehv"
# Default
# provider = "libkrun"

[network]
[secrets]
[configmaps]
